version: '3.9'

services:
  auth-app:
    container_name: auth-app
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: auth_db
      POSTGRES_PORT: 5432

  db:
    container_name: auth_db
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: test
      POSTGRES_SSLMODE: disable
    ports:
      - "5440:5432"